# This file is a template, to be fleshed out by running:
#    plsync/mlabconfig.py --format=scraper_kubernetes \
#        --template_input=deploy.yml \
#        --template_output=deployment/{{site}}-{{node}}-{{experiment}}-{{rsync_module}}.yml
#
# The plsync directory and its contents may be found in:
#    https://github.com/m-lab/operator
# The template, once filled out, specifies the kubernetes deployment for
# scraper.  The deployment may be deployed with:
#    kubectl create -f scraper_deploy.yml
# If the deployment fails with the error "namespace does not exist", then run
#    kubectl create -f namespace.yml
# to create the namespace, and then try the deployment again.
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
  namespace: scraper
  labels:
    app: {{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
      name: {{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
      labels:
        app: {{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
        service: scraper
        experiment: {{experiment}}
        machine: {{machine}}
        rsync_module: {{rsync_module}}
    spec:
      containers:
        - name: {{site_safe}}-{{node_safe}}-{{experiment_safe}}-{{rsync_module_safe}}
          image: # Travis or the human operator should fill this in
          env:
            - name: RSYNC_MODULE
              value: {{rsync_module}}
            - name: RSYNC_HOST
              value: {{rsync_host}}
            - name: GCS_BUCKET
              value: # Travis or the human operator should fill this in
            - name: DATASTORE_NAMESPACE
              value: # Travis or the human operator should fill this in
            - name: MAX_UNCOMPRESSED_SIZE
              value: 50000000
          resources:
            requests:
              memory: "200Mi"
              cpu: "30m"
            limits:
              memory: "200Mi"
              cpu: "30m"
