# This file is a template, to be fleshed out by running:
#    plsyc/mlabconfig.py --scraper_kubernetes \
#                        --template_yaml=deploy.yml > scraper_deploy.yml
# The plsync directory and its contents may be found in:
#    https://github.com/m-lab/operator
# The template, once filled out, specifies the kubernetes deployment for
# scraper.  The deployment may be deployed with:
#    kubectl create -f scraper_deploy.yml
# If the deployment fails with the error "namespace does not exist", then run
#    kubectl create -f namespace.yml
# to create the namespace, and then try the deployment again.
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {site}-{node}-{experiment}-{rsync_module}
  namespace: scraper
  labels:
    app: {site}-{node}-{experiment}-{rsync_module}
    version: test
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
      name: {site}-{node}-{experiment}-{rsync_module}
      labels:
        app: {site}-{node}-{experiment}-{rsync_module}
        version: test
    spec:
      containers:
        - name: {site}-{node}-{experiment}-{rsync_module}
          image: gcr.io/mlab-sandbox/github-pboothe-scraper-fix-mem-pressure:b4a744e88ed48ed4fa055ebf49d99d824ebcf9bf
          env:
            - name: RSYNC_MODULE
              value: {rsync_module}
            - name: RSYNC_HOST
              value: {rsync_host}
            - name: GCS_BUCKET
              value: mlab-scraper-sandbox
            - name: DATASTORE_NAMESPACE
              value: scraper
          resources:
            requests:
              memory: "20Mi"
              cpu: "20m"
